[package]
name = 'minipolars'
version = '0.1.0'
edition = '2021'


[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr"} 
polars = {version = "0.24.0", features = ["abs","cum_agg","lazy","abs","round_series","csv-file","serde","parquet","object", "cross_join", "semi_anti_join"]}
flume = "*"
state = "*"
