[package]
name = 'minipolars'
version = '0.1.0'
edition = '2021'


[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = '*'
polars = {version = "0.24.0", features = ["abs","cum_agg","lazy","abs","round_series","csv-file","serde","parquet","object"]}
flume = "*"
state = "*"
#extendr-api = {path = "../../../extendr/extendr-api"}
#extendr-engine = { path = "../../../extendr/extendr-engine"}

