[package]
name = "r-polars"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "lib"]

[profile.release]
panic = "unwind"

[dependencies]
savvy = "0.6.4"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "318ec405632410a41f634de7aeff46e89a25eab9", default-features = false }
polars-error = { git = "https://github.com/pola-rs/polars.git", rev = "318ec405632410a41f634de7aeff46e89a25eab9", default-features = false }
thiserror = "1"

[dependencies.polars]
git = "https://github.com/pola-rs/polars.git"
rev = "318ec405632410a41f634de7aeff46e89a25eab9"
features = ["dtype-full", "lazy", "propagate_nans"]
