# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    # runs-on: ubuntu-latest
    # # Only restrict concurrency for non-PR jobs
    # concurrency:
    #   group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }} rust-${{ matrix.config.rust-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #          - { os: macOS-latest, r: "release", rust-version: "nightly" }
          #          - { os: ubuntu-latest, r: "release", rust-version: "nightly" }
          - { os: windows-latest, r: "release", rust-version: "nightly" } #skip windows fails nightly

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.PAT_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - name: show rustup targets
        if: runner.os == 'Windows'
        run: |
          rustup show
          rustup toolchain remove stable-x86_64-pc-windows-msvc
          rustup toolchain install nightly-x86_64-pc-windows-gnu
          rustup default nightly-x86_64-pc-windows-gnu
          rustup show

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick@6
          brew install libgit2
          brew install harfbuzz fribidi

      - name: Install ubntu SYSTEM REQUIREMENTS
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libfontconfig1-dev
          sudo apt-get install -y libfreetype6-dev
          sudo apt-get install -y libfribidi-dev
          sudo apt-get install -y git
          sudo apt-get install -y make
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libgit2-dev
          sudo apt-get install -y libicu-dev
          sudo apt-get install -y libjpeg-dev
          sudo apt-get install -y libpng-dev
          sudo apt-get install -y libtiff-dev
          sudo apt-get install -y libxml2-dev
          sudo apt-get install -y libssl-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false
          install-r: false
          rtools-version: "42"
          update-rtools: true
          Ncpus: 2

      - name: check rtools
        run: |
          install.packages("pkgbuild")  
          print(pkgbuild::rtools_path())

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: build package
        run: devtools::install(quick = TRUE)
        shell: Rscript {0}

      - name: build binary
        run: devtools::build(binary = TRUE, args = c('--preclean'))
        shell: Rscript {0}

      - name: print files
        run: print(list.files(recursive = TRUE))
        shell: Rscript {0}

      - name: Build site
        if: runner.os == 'Linux'
        run: pkgdown::build_site_github_pages(new_process = FALSE, devel=TRUE, install = FALSE, examples=TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: runner.os == 'Linux' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: main
          folder: docs
          repository-name: sorhawell/sorhawell.github.io
          token: ${{ secrets.PAT_TOKEN }}
