# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    # runs-on: ubuntu-latest
    # # Only restrict concurrency for non-PR jobs
    # concurrency:
    #   group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }} rust-${{ matrix.config.rust-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: windows-latest, r: 'release', rust-version: 'nightly'}  #skip windows fails nightly
#          - {os: macOS-latest,   r: 'release', rust-version: 'nightly'}
          - {os: ubuntu-latest,  r: 'release', rust-version: 'nightly'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: nightly
      #     default: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          install-r : false


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:  any::pkgdown, local::.
          cache: true
          cache-version: 1

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE, examples=FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          clean: false
          branch: gh-pages
          folder: docs
          repository-name: sorhawell/sorhawell.github.io


