# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, fix_github_actions]
    tags:
      - "**" # Push events to every tag including hierarchical tags like v1.0/beta
  pull_request:
    branches: [main, fix_github_actions]
  release:
    types: [published]

  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    needs: deploy
    # runs-on: ubuntu-latest
    # # Only restrict concurrency for non-PR jobs
    # concurrency:
    #   group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }} rust-${{ matrix.config.rust-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #- { os: macOS-latest, r: "release", rust-version: "nightly" }
          - { os: ubuntu-latest, r: "release", rust-version: "nightly" }
          # - {
          #     os: windows-latest,
          #     r: "release",
          #     rust-version: "nightly-gnu",
          #     rtools-version: "42",
          #   }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      TOOLCHAIN: ${{ matrix.config.rust-version }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: check if release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo this is a release

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.config.rust-version }}
          default: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick@6
          brew install libgit2
          brew install harfbuzz fribidi

      - name: Install ubntu SYSTEM REQUIREMENTS
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libfontconfig1-dev
          sudo apt-get install -y libfreetype6-dev
          sudo apt-get install -y libfribidi-dev
          sudo apt-get install -y git
          sudo apt-get install -y make
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libgit2-dev
          sudo apt-get install -y libicu-dev
          sudo apt-get install -y libjpeg-dev
          sudo apt-get install -y libpng-dev
          sudo apt-get install -y libtiff-dev
          sudo apt-get install -y libxml2-dev
          sudo apt-get install -y libssl-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false
          install-r: true
          rtools-version: "42"
          update-rtools: true
          Ncpus: 2

      - name: show rustup targets + rtools gcc
        if: runner.os == 'Windows'
        run: |
          rustup show
          dir -Path c:\rtools* -Filter *gcc*.exe* -Recurse | %{$_.FullName}
          echo echo $env:path

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      # - name: build package + test
      #   run: |
      #     devtools::install(quick = TRUE)
      #     devtools::test(stop_on_failure = TRUE)
      #   shell: Rscript {0}

      # - name: build binary
      #   run: devtools::build(binary = TRUE, args = c('--preclean'))
      #   shell: Rscript {0}

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   #if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     #token: ${{ secrets.PAT_TOKEN }}
      #     tag_name: ${{ github.run_number }}
      #     files: ../rpolars_*

      - name: print files
        run: print(list.files("..",recursive = TRUE,full.names=TRUE))
        shell: Rscript {0}

      - name: print wd
        run: print(getwd())
        shell: Rscript {0}

      - name: Build site
        if: runner.os == 'Linux'
        run: pkgdown::build_site_github_pages(new_process = FALSE, devel=TRUE, install = FALSE, examples=TRUE)
        shell: Rscript {0}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rpolars-docs
          retention-days: 5
          path: |
            docs
  deploy:
    runs-on: ubuntu-latest
    name: deploy docs
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      docs_key: ${{ secrets.DEPLOY_DOCS }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    #needs: pkgdown
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/download-artifact@v3
      #   with:
      #     name: rpolars-docs

      - name: Display structure of downloaded files
        run: |

          mkdir docs
          echo "# hello to rpolars.github.io" > docs/README.md

          ls

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_DOCS }}
          name: id_rsa # optional
          known_hosts: unnecessary
          #config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: Deploy to GitHub pages 🚀
        if: runner.os == 'Linux' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: main
          folder: docs
          repository-name: rpolars/rpolars.github.io
          #ssh-key: docs_key
          #token: ${{ secrets.PAT_TOKEN }}
